React1
ijeomaodinko/React-Project pull request #2
Opened 2022-09-09 19:05 UTC by ijeomaodinko

**Description**
This React capstone project ([remember what are they?](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/capstone_intro.md))is about building a mobile web application to check a list of metrics (numeric values) that you will create making use of React and Redux.

You will select an API that provides numeric data about a topic that you like and then build the webapp around it. The webapp will have several pages:

one page with a list of items that could be filtered by some parameters; in the example below, it's a list of metrics that can be filtered by the country (imagine a search field to introduce the country name like Italy, Croatia, etc.). This page should be your homepage.
one page for the item details; in the example, the detail page for Czech Republic cities with number of views.
Home page

When the page loads, the webapp shows the list of categories that could be filtered out by some parameter, for example by the category name.
Along with the category name, you will display some numeric values per category that come from the API.
When the user clicks (or taps) on a category item, the application navigates to the details page.
Details page
In the details page, the webapp retrieves data from the API to show detailed data in the category.
When the user clicks on the "Back" button (<), the user navigates to the home page.

The link is the page deployment but is still in progress. Thanks

https://www.loom.com/share/5a3d5650f2fd4c5ea1a2850ca7c7af1d

2022-09-09 19:53 UTC, Deepakdanger requested changes
Hi @ijeomaodinko, 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight :100: 
- No linter error :heavy_check_mark: 
- Website looks professional :+1: 

## Required Changes ♻️
- [ ] Whenever i search anything, instead of mathing tiles ,I got this empty tile.KIndly fix this.
![Screenshot from 2022-09-10 01-17-48](https://user-images.githubusercontent.com/26767383/189432543-cda4bbae-f508-49f5-911d-87aa5ba577d2.png)

- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-09 19:53 UTC, Deepakdanger commented on README.md
> +[Live Demo Link](https://livedemo.com)
- [ ] Kindly add the proper link to the live demo.
 - The student deploys the application using Heroku, Netlify or GitHub Pages.

2022-09-09 19:53 UTC, Deepakdanger commented on src/components/Detail.js
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
- [ ] KIndly remove this line & solve the linter manually.

2022-09-09 19:53 UTC, Deepakdanger commented on src/components/Home.js
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
- [ ] KIndly remove this line & solve the linter manually.

2022-09-10 10:41 UTC, ijeomaodinko commented
The required changes are fixed.
The tile is showing information.
The commands were removed.
The site is showing

2022-09-10 11:06 UTC, zhadier requested changes
# Hi @ijeomaodinko  👋  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🌤️ 

<img src="https://media4.giphy.com/media/5wWf7GR2nhgamhRnEuA/giphy.gif"/>

 ## Highlights

✔️ No linter errors
✔️ GitFlow was setup correctly
✔️ Professional pull request title and description

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question @zhadier so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-10 11:06 UTC, zhadier commented on src/components/Home.js
> +          </select>
- [ ] Kindly ensure that you keep the search bar from the previous review, as that is the project requirement, to be able to filter using a specific category value, like the name. This functionality is quite easy to implement and can be found in most websites so learning how to create a search bar is imperative. You may use the following code as a guide to filter the list of bit coins you get from the reducer using the input value of a search bar. Kindly implement the search bar.

``` js
 let filteredList = bitcoinsList;
 const handleSearch = (evt) => {
    setSearch(evt.target.value); // State to control the input of the search bar
    if (evt.target.value.trim().length === 0) {
      filteredList = bitcoinsList;
    } else {
      const val = evt.target.value.trim().toLowerCase();
      filteredList = bitcoinsList.filter((bitcoin) => bitcoin.name.toLowerCase().includes(val));
    }
  };
```

2022-09-10 11:06 UTC, zhadier commented on src/redux/Detail.js
> +// const initialState = [{ id: 'bitcoin', symbol: 'BTC' }];
- [ ] Kindly remove commented out code from your repo as it is considered bad for maintainability and manageability.

2022-09-10 14:04 UTC, ahmetbozaci requested changes
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️ 
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

@ijeomaodinko  ✋🏼 
#### Great work on making the changes requested by a previous reviewer 👏 
#### You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
___ 

### 💯  Highlights 💯
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️
___

### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._
___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-09-10 14:04 UTC, ahmetbozaci commented on src/App.js
> +// import { BrowserRouter, Routes, Route } from 'react-router-dom';
- [ ] Like the last code reviewer said kindly remove commented code to make clean code.

2022-09-10 14:14 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🍾✔🎉**
Hello @ijeomaodinko 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Your linters are passing all the checks
- You asked for the changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-09 12:31 UTC, merged